name: ttipm
channels:
  - conda-forge
dependencies:
  - python=3.10.13
  - numpy==2.2.5
  - scipy==1.15.3
  - cvxpy==1.6.4
  - opt_einsum==3.4.0
  - Cython==3.0.11
  - pip
  - pip:
      - scikit-sparse