from time import time
from utils import *
from optimiser import ILPSolver, AnswerSetSolver

vocab_size = 5
x = Atom(vocab_size, "x")
y = Atom(vocab_size, "y")
z = Atom(vocab_size, "z")
w = Atom(vocab_size, "w")
u = Atom(vocab_size, "u")
h = Hypothesis()
const_space = ConstraintSpace()
e_0 = Boolean_Function(x & w)
const_space.exists_S(h << e_0)
e_1 = Boolean_Function(x & y & z)
const_space.forall_S(h << e_1)
e_2 = Boolean_Function(x << (y & z))
const_space.exists_S(h << e_2)
e_3 = Boolean_Function(x)
const_space.forall_S(h >> e_3)
e_4 = Boolean_Function(x & ~z & ~y)
const_space.exists_S(h << e_4)
e_5 = Boolean_Function(u & w)
const_space.exists_S(h << e_5)
opt = ILPSolver(const_space, vocab_size)
t_1 = time()
hypothesis = opt.find_feasible_hypothesis()
print("Shapes: ", [t.shape for t in hypothesis])
t_2 = time()
print(get_CNF([x, y, z, w, u], hypothesis), flush=True)
print("Equality constraint Score: ", [jnp.sum(jnp.abs(c(hypothesis))) for c in const_space.eq_constraints])
print("Inequality constraint Score: ", [jnp.sum(c(hypothesis)) for c in const_space.iq_constraints])
print("Score:", boolean_criterion(len(hypothesis))(hypothesis), tt_inner_prod(hypothesis, hypothesis))
print(f"Total time taken: {t_2-t_1}s.")
asp_solver = AnswerSetSolver([x, y, z, w, u])
X = asp_solver.get_minimal_answer_set(hypothesis)
print(X)