from utils import *

const_space = ConstraintSpace()
x = const_space.Atom("x")
y = const_space.Atom("y")
z = const_space.Atom("z")
w = const_space.Atom("w")
u = const_space.Atom("u")
h = const_space.Hypothesis("h_0")
const_space.there_exists(h << (x & w))
const_space.for_all(h << (x & y & z))
const_space.there_exists(h << (x << (y & z)))
const_space.for_all(h >> x)
const_space.there_exists(h << (x & ~z & ~y))
const_space.there_exists(h | ~(u & w))
const_space.project(h)