abs_tol: 0.001
dim: 8
epsilonDash: 2.0
epsilonDashineq: 0.001
gap_tol: 0.0003
mals_restarts: 2
max_iter: 25
max_refinement: 7
op_tol: 0.0001
seeds:
- 208
- 493
- 324
- 325
- 9299
verbose: false
warm_up: 3
