abs_tol: 9e-4
dim: 10
epsilonDash: 2.0
epsilonDashineq: 1.0e-03
gap_tol: 0.0003
mals_restarts: 2
max_iter: 25
max_refinement: 5
op_tol: 0.0001
seeds:
- 765
#- 932
#- 42
#- 492
#- 482
verbose: true
warm_up: 3
