abs_tol: 9e-4
dim: 6
epsilonDash: 2.0
epsilonDashineq: 2.0
gap_tol: 0.0005
mals_restarts: 2
max_iter: 25
max_refinement: 5
op_tol: 0.0001
seeds:
- 291
#- 932
#- 42
#- 492
#- 482
verbose: false
warm_up: 3
