abs_tol: 9e-4
dim: 11
epsilonDash: 2.0
epsilonDashineq: 1.0e-03
gap_tol: 0.0003
mals_restarts: 2
max_iter: 25
max_refinement: 6
op_tol: 0.0001
seeds:
- 764
- 493
- 324
- 325
- 9299
verbose: false
warm_up: 3
