# Common
dim: !!int 3
max_rank: !!int 3 # (2)
seeds: [68]  # Tier 1: 52, 68, 23, 9175, 212 Tier 2: (87 maybe) Tier 3:
gap_tol: !!float 4e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 25
warm_up: !!int 0