# Common
dim: !!int 4
max_rank: !!int 2 # 4
seeds: [692] # Tier 1: 5, 692, 928 (slow), Tier 2: (87 maybe) Tier 3: 9402
gap_tol: !!float 5e-4
verbose: True
# TT-IPM
op_tol: !!float 5e-5
max_iter: !!int 30
warm_up: !!int 0