# Common
dim: !!int 1
max_rank: !!int 1
seeds: [5]
feasibility_tol: !!float 5e-5
centrality_tol: !!float 5e-3
verbose: True
# TT-IPM
tau: 0.9
op_tol: !!float 5e-5
max_iter: !!int 3
# Sketchy CGAL
sketch_cgal_rank: !!int 10
duality_tol: 0.5