abs_tol: 0.001
dim: 3
lambdaStar: 1.0
lambdaStarIneq: 0.00000001
gap_tol: 0.0005
mals_restarts: 2
max_iter: 25
max_refinement: 5
op_tol: 0.0001
seeds:
- 256
#- 493
#- 324
#- 325
#- 9299
verbose: true
warm_up: 3