# Common
dim: !!int 2
max_ranks: [1]
seeds: [83]  # !!53, 68, 23, 9175, 212!! 
gap_tol: !!float 1e-3
verbose: True
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 25
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 1
