# Common
dim: !!int 4
max_rank: !!int 2 # 4
seeds: [0, 692, 44, 5, 77] # Tier 1: 0, 692, 44, 5, 77 (slow) Tier 2: 99, 24, (87 maybe) Tier 3: 9402, 21, 928
gap_tol: !!float 5e-4
verbose: False
# TT-IPM
op_tol: !!float 5e-5
max_iter: !!int 25
warm_up: !!int 0