# Common
dim: !!int 3
max_rank: !!int 2
seeds: [5] #[5, 6, 7, 8, 9]
feasibility_tol: !!float 1e-3
centrality_tol: !!float 1e-3
verbose: True
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 16
# Sketchy CGAL
sketch_cgal_rank: !!int 10
duality_tol: 0.5