# Common
dim: !!int 3
max_rank: !!int 2
seeds: []  # Tier 1: 52, 68, 23, Tier 2: (87 maybe) Tier 3:
gap_tol: !!float 5e-4
verbose: False
# TT-IPM
op_tol: !!float 5e-5
max_iter: !!int 20
warm_up: !!int 3