# Common
dim: !!int 3
max_ranks: [1]
seeds: [53, 68, 23, 9175, 212]  # !!53, 68, 23, 9175, 212!! 
gap_tol: !!float 5e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 25
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 1