# Common
dim: !!int 3
seeds: [710]  # !!710, 68, 23, 975, 212!!
gap_tol: !!float 5e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-4
abs_tol: !!float 9e-4
max_iter: !!int 15
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 3
epsilonDash: !!float 1
epsilonDashineq: !!float 1e-8