# Common
dim: !!int 4
max_ranks: [1]
seeds: [0] # !!0, 692, 44, 5, 77 (slow)!!
gap_tol: !!float 5e-4
verbose: True
# TT-IPM
op_tol: !!float 5e-5
max_iter: !!int 25
warm_up: !!int 0
mals_restarts: !!int 3
max_refinement:  !!int 5
epsilonDash: !!float 1