# Common
dim: !!int 2
max_rank: !!int 2
seeds: [5]
gap_tol: !!float 2e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 15
warm_up: !!int 3
mals_rank_restriction: !!int 24
mals_restarts: !!int 3
max_refinement:  !!int 5