# Common
dim: !!int 3
max_rank: !!int 2
seeds: [5, 6, 7, 8, 9]
gap_tol: !!float 2e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 18
# Sketchy CGAL
sketch_cgal_rank: !!int 10
duality_tol: 0.5