# Common
dim: !!int 1
max_rank: !!int 1
seeds: [5]
feasibility_tol: !!float 1e-3
centrality_tol: !!float 1e-3
verbose: True
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 20
# Sketchy CGAL
sketch_cgal_rank: !!int 10
duality_tol: 0.5