dim: 4
epsilonDash: 1.0
gap_tol: 0.0006
mals_restarts: 2
max_iter: 13
max_refinement: 3
op_tol: 0.0001
abs_tol: 9e-4
seeds:
- 9428
- 375
- 482
- 434
- 928
verbose: true
warm_up: 3
epsilonDashineq: !!float 1e-8
