# Common
dim: !!int 2
max_ranks: [1]
seeds: [5, 4, 2, 12, 3]
gap_tol: !!float 2e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 15
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 1