# Common
dim: !!int 4
max_ranks: [1]
seeds: [4922, 72, 313, 582, 2] # !!4922, 72, 313, 582, 2!!
gap_tol: !!float 8e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 28
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement: !!int 5
epsilonDash: !!float 1