# Common
dim: !!int 9
max_rank: !!int 4
seeds: [42, 592, 83, 75, 124] # Tier 1: !!42, 592, 83, 75, 124!!
gap_tol: !!float 3e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 20
warm_up: !!int 3
mals_rank_restriction: !!int 34
mals_restarts: !!int 2
# Sketchy CGAL
sketch_cgal_rank: !!int 256