# Common
dim: !!int 8
max_rank: !!int 4
seeds: [8, 5, 41, 7, 9] # !! 8, 5, 41, 7, 9 !!
gap_tol: !!float 3e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 18
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
