# Common
dim: !!int 6
max_rank: !!int 4
seeds: [7] # Tier 1: 7, 6, 8, 5, 9 Tier 2: Tier 3:
gap_tol: !!float 4e-4
verbose: True
# TT-IPM
op_tol: !!float 4e-5
max_iter: !!int 18
warm_up: !!int 3
mals_rank_restriction: !!int 20
mals_restarts: !!int 2
# Sketchy CGAL
sketch_cgal_rank: !!int 32
