# Common
dim: !!int 10
seeds: [42, 592, 83, 75, 124] # !!42, 592, 83, 75, 124!!
gap_tol: !!float 3e-4
verbose: false
# TT-IPM
op_tol: !!float 1e-4
abs_tol: !!float 6e-4
max_iter: !!int 25
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 2