# Common
dim: !!int 10
max_rank: !!int 4
seeds: [7]
feasibility_tol: !!float 1e-4
centrality_tol: !!float 8e-4
verbose: True
# TT-IPM
tau: 0.9
op_tol: !!float 1e-4
max_iter: !!int 10
# Sketchy CGAL
sketch_cgal_rank: !!int 50
duality_tol: 0.5