# Common
dim: !!int 3
max_rank: !!int 1
seeds: [5, 6, 7, 8, 9]
feasibility_tol: !!float 5e-5
centrality_tol: !!float 5e-3
verbose: False
# TT-IPM
tau: 0.9
op_tol: !!float 8e-4
max_iter: !!int 20
direction: "XZ+ZX"
# Sketchy CGAL
sketch_cgal_rank: !!int 2
duality_tol: 0.5