# Common
dim: !!int 10
max_rank: !!int 4
seeds: [9482, 9254, 3181] # Tier 1: 42, 23, 666, Tier 2: 43 (good but very slow 12k), 9254 (good but slow 13k) Tier 3:
gap_tol: !!float 2e-4
verbose: True
# TT-IPM
op_tol: !!float 5e-6
max_iter: !!int 20
warm_up: !!int 3
# Sketchy CGAL
sketch_cgal_rank: !!int 512
