# Common
dim: !!int 8
max_ranks: [1]
seeds: [8, 41, 5 , 7, 9] # !! 8, 41,    5 , 7, 9 !!
gap_tol: !!float 3e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-4
abs_tol: !!float 6e-4
max_iter: !!int 24
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 2