# Common
dim: !!int 5
max_rank: !!int 4
seeds: [5]
feasibility_tol: !!float 5e-5
centrality_tol: !!float 0.1
verbose: True
# TT-IPM
tau: 0.9
op_tol: !!float 8e-4
max_iter: !!int 12
# Sketchy CGAL
sketch_cgal_rank: !!int 2
duality_tol: 0.5
# SAFE AND TESTED