# Common
dim: !!int 4
max_rank: !!int 4
seeds: [5]
feasibility_tol: !!float 5e-5
centrality_tol: !!float 5e-3
verbose: True
# TT-IPM
tau: 0.9
op_tol: !!float 8e-4
max_iter: !!int 25
direction: "XZ+ZX"
# Sketchy CGAL
sketch_cgal_rank: !!int 2
duality_tol: 0.5