# Common
dim: !!int 6
max_rank: !!int 4
seeds: [8] # 5, 6, 7 safe
feasibility_tol: !!float 5e-5
centrality_tol: !!float 5e-3
verbose: True
# TT-IPM
tau: 0.9
op_tol: !!float 1e-4
max_iter: !!int 15
direction: "XZ+ZX"
# Sketchy CGAL
sketch_cgal_rank: !!int 10
duality_tol: 0.5