# Common
dim: !!int 10
max_rank: !!int 4
seeds: [5, 6, 7, 8, 9] # Tier 1: Tier 2: Tier 3:
gap_tol: !!float 2e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-6
max_iter: !!int 20
warm_up: !!int 8
# Sketchy CGAL
sketch_cgal_rank: !!int 512
