# Common
dim: !!int 7
max_ranks: [1, 2, 3, 4, 5]
seeds: [5, 7, 91, 9, 84] # !! 5, 7, 91, 9, 84 !!
gap_tol: !!float 3e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 22
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 2