# Common
dim: !!int 8
max_rank: !!int 4
seeds: [5, 41, 7, 8, 9] # Tier 1: 5, 41, 7, 8, 9 Tier 2: 83 (good but slow 2k), 86 (good but slow 4k), 90 (good but slow 2k), 6 (good but slow 3k) Tier 3:
gap_tol: !!float 4e-4
verbose: True
# TT-IPM
op_tol: !!float 5e-5
max_iter: !!int 18
warm_up: !!int 3
mals_rank_restriction: !!int 33
mals_restarts: !!int 3
# Sketchy CGAL
sketch_cgal_rank: !!int 128
