# Common
dim: !!int 10
max_rank: !!int 4
seeds: [7]
feasibility_tol: !!float 5e-5
centrality_tol: !!float 9e-4
verbose: True
# TT-IPM
tau: 0.9
op_tol: !!float 1e-4
max_iter: !!int 3
direction: "XZ+ZX"
# Sketchy CGAL
sketch_cgal_rank: !!int 50
duality_tol: 0.5