# Common
dim: !!int 9
max_rank: !!int 4
seeds: [5, 6, 7, 8, 9]
feasibility_tol: !!float 8e-4
centrality_tol: !!float 8e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 15
# Sketchy CGAL
sketch_cgal_rank: !!int 50
duality_tol: 0.5