# Common
dim: !!int 9
max_rank: !!int 4
seeds: [4928, 3819, 83,  21] # Tier 1: 592, Tier 2: Tier 3: 96, 353, 5
gap_tol: !!float 2e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-5
max_iter: !!int 20
warm_up: !!int 3
# Sketchy CGAL
sketch_cgal_rank: !!int 256
