dim: !!int 13
seeds: 
- 83
#- 45
#- 23
#- 53
#- 12 
gap_tol: !!float 3e-4
verbose: true
op_tol: !!float 1e-4
abs_tol: !!float 0.001
max_iter: !!int 30
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 6
lambdaStar: 1.0
