# Common
dim: !!int 10
seeds: [48] # !! 48, 23, 235, 35, 14 !! 
gap_tol: !!float 3e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
abs_tol: !!float 0.001
max_iter: !!int 30
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 6
epsilonDash: !!float 1