# Common
dim: !!int 8
max_rank: !!int 4
seeds: [24, 8, 122, 416, 91] # !!24, 8, 122, 416, 91!!
gap_tol: !!float 3e-4
verbose: False
# TT-IPM
op_tol: !!float 5e-4
max_iter: !!int 18
warm_up: !!int 3
mals_rank_restriction: !!int 30
mals_restarts: !!int 2
max_refinement:  !!int 5
# Sketchy CGAL
sketch_cgal_rank: !!int 32