# Common
dim: !!int 9
max_rank: !!int 4
seeds: [3, 22, 14, 32, 55] #[0, 1, 3, 4, 5] #[0:0.45, 1: 0.82, 3:0.79, 4:0.83, 5:0.93] prefer 3, 4 for speed
gap_tol: !!float 2e-4
verbose: False
# TT-IPM
op_tol: !!float 5e-5
max_iter: !!int 30
# Sketchy CGAL
sketch_cgal_rank: !!int 64