# Common
dim: !!int 9
max_rank: !!int 4
seeds: [33] # Tier 1: 9313, 3333, 33333, 24, Tier 2: 66, 8399, 22, Tier 3: 33, Tier faulty: 45
gap_tol: !!float 2e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-5
max_iter: !!int 35
warm_up: !!int 8
# Sketchy CGAL
sketch_cgal_rank: !!int 64