# Common
dim: !!int 6
max_rank: !!int 4
seeds: [73] #[73, 54, 624, 7, 9] # Tier 1: 73, 54, 624, 7, 9 Tier 2: 6, 8, Tier 3: 5
gap_tol: !!float 3e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 25
warm_up: !!int 3
mals_rank_restriction: !!int 20
mals_restarts: !!int 3
# Sketchy CGAL
sketch_cgal_rank: !!int 8