# Common
dim: !!int 6
max_rank: !!int 4
seeds: [5] #[5, 6, 7, 8, 9]
feasibility_tol: !!float 5e-4
centrality_tol: !!float 2e-4
verbose: True
# TT-IPM
op_tol: !!float 8e-4
max_iter: !!int 25
# Sketchy CGAL
sketch_cgal_rank: !!int 8
duality_tol: 0.1