# Common
dim: !!int 10
max_rank: !!int 4
seeds: [8]
feasibility_tol: !!float 1e-4
centrality_tol: !!float 0.5
verbose: True
# TT-IPM
tau: 0.9
op_tol: !!float 1e-4
max_iter: !!int 16
direction: "XZ"
# Sketchy CGAL
sketch_cgal_rank: !!int 100
duality_tol: 0.5