# Common
dim: !!int 10
max_rank: !!int 4
seeds: [6]
feasibility_tol: !!float 5e-5
centrality_tol: !!float 1e-3
verbose: False
# TT-IPM
tau: 0.9
op_tol: !!float 1e-4
max_iter: !!int 20
direction: "XZ"
# Sketchy CGAL
sketch_cgal_rank: !!int 10
duality_tol: 0.5