# Common
dim: !!int 8
max_ranks: [2]
seeds: [24, 8, 122, 416, 91] # !!24, 8, 122, 416, 91!!
gap_tol: !!float 3e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
abs_tol: !!float 6e-4
max_iter: !!int 26
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 1