# Common
dim: !!int 2
max_rank: !!int 1
seeds: [5]
feasibility_tol: !!float 8e-4
centrality_tol: !!float 8e-4
verbose: False
# TT-IPM
tau: 0.9
op_tol: !!float 1e-4
max_iter: !!int 20
# Sketchy CGAL
sketch_cgal_rank: !!int 10
duality_tol: 0.5