# Common
dim: !!int 10
max_rank: !!int 4
seeds: [94, 56, 3333, 33333, 45]
gap_tol: !!float 2e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-6
max_iter: !!int 30
# Sketchy CGAL
sketch_cgal_rank: !!int 128