# Common
dim: !!int 6
max_ranks: [1, 2]
seeds: [73, 54, 624, 7, 9] # !! 73, 54, 624, 7, 9 !!
gap_tol: !!float 3e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 22
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 1