# Common
dim: !!int 9
max_rank: !!int 4
seeds: [0, 1] #[3:0.79, 4:0.83, 5:0.93]
gap_tol: !!float 2e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 25
# Sketchy CGAL
sketch_cgal_rank: !!int 64