# Common
dim: !!int 9
max_ranks: [3]
seeds: [9402, 9313, 332, 342, 24] # !!9402, 9313, 332, 342, 24!!
gap_tol: !!float 3e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
abs_tol: !!float 6e-4
max_iter: !!int 28
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 1