dim: !!int 7
max_rank: !!int 4
seeds: [5]
op_tol: !!float 5e-4
feasibility_tol: !!float 5e-5
centrality_tol: !!float 5e-3
max_iter: !!int 25
tau: !!float 0.9
sigma_intp: 0.5
direction: "XZ"
verbose: True