# Common
dim: !!int 6
seeds: [73] # !! 73, 54, 624, 7, 9 !!
gap_tol: !!float 3e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-4
abs_tol: !!float 0.001
max_iter: !!int 22
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 1