# Common
dim: !!int 9
max_ranks: [1]
seeds: [9402, 9313, 3333, 33333, 24] # !!9402, 9313, 3333, 33333, 24!!
gap_tol: !!float 3e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 20
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5