# Common
dim: !!int 10
max_rank: !!int 4
seeds: [48, 937, 23, 22, 89] # Tier 1: 48, (14, 937, 23, 22) Tier 2: 45 (0.24 compl slackness), Tier 3: 94
gap_tol: !!float 4e-4
verbose: True
# TT-IPM
op_tol: !!float 5e-4
max_iter: !!int 38
warm_up: !!int 0
mals_rank_restriction: !!int 36
mals_restarts: !!int 3
# Sketchy CGAL
sketch_cgal_rank: !!int 128