# Common
dim: !!int 7
max_rank: !!int 4
seeds: [5] # !!5, 34, 53, 5345, 84, 51!!
gap_tol: !!float 3e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 30
warm_up: !!int 3
mals_rank_restriction: !!int 25
mals_restarts: !!int 2
max_refinement:  !!int 5