# Common
dim: !!int 9
max_rank: !!int 4
seeds: [5, 6, 7, 8, 9] # solved: 5, 6
feasibility_tol: !!float 1e-3
centrality_tol: !!float 1e-3
verbose: False
# TT-IPM
op_tol: !!float 1e-5
max_iter: !!int 25
# Sketchy CGAL
sketch_cgal_rank: !!int 64
duality_tol: 0.1