# Common
dim: !!int 8
seeds: 
- 24
#- 8
#- 122
#- 416
#- 91
gap_tol: !!float 3e-4
verbose: true
# TT-IPM
op_tol: !!float 1e-4
abs_tol: !!float 0.001
max_iter: !!int 26
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5
epsilonDash: !!float 1