# Common
dim: !!int 12
seeds: [87, 43, 23, 5, 6] 
gap_tol: !!float 3e-4
verbose: false
# TT-IPM
op_tol: !!float 1e-4
abs_tol: !!float 6e-4
max_iter: !!int 30
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 6
epsilonDash: !!float 1