# Common
dim: !!int 10
max_ranks: [1]
seeds: [48, 14, 937, 23, 22] # !! 48, 14, 937, 23, 22 !!
gap_tol: !!float 3e-4
verbose: False
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 30
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 6