# Common
dim: !!int 8
max_rank: !!int 4
seeds: [24] #[5, 6, 7, 8, 9] # Tier 1: 24, 8, 122, 416, 91, Tier 2: 88 (slow but good), 94, Tier 3: 5, 6 (very slow but good), 7, 53, 28
gap_tol: !!float 2e-4
verbose: True
# TT-IPM
op_tol: !!float 5e-5
max_iter: !!int 33
warm_up: !!int 3
# Sketchy CGAL
sketch_cgal_rank: !!int 32