# Common
dim: !!int 9
max_rank: !!int 4
seeds: [45] #[245, 3333, 33333, 3, 4] # Tier 1: [3333, 33333], Tier 2: [3]
gap_tol: !!float 2e-4
verbose: True
# TT-IPM
op_tol: !!float 5e-6
max_iter: !!int 30
# Sketchy CGAL
sketch_cgal_rank: !!int 64