# Common
dim: !!int 8
max_ranks: [1]
seeds: [8] # !!24, 8, 122, 416, 91!!
gap_tol: !!float 3e-4
verbose: True
# TT-IPM
op_tol: !!float 1e-4
max_iter: !!int 18
warm_up: !!int 3
mals_restarts: !!int 2
max_refinement:  !!int 5