# Common
dim: !!int 7
max_rank: !!int 4
seeds: [5, 6, 7, 8, 9]
gap_tol: !!float 2e-4
verbose: False
# TT-IPM
op_tol: !!float 4e-4
max_iter: !!int 25
# Sketchy CGAL
sketch_cgal_rank: !!int 16
duality_tol: 0.1