# Common
dim: !!int 10
max_rank: !!int 4
seeds: [5, 6, 7, 8, 9]
feasibility_tol: !!float 1e-3
centrality_tol: !!float 1e-3
verbose: False
# TT-IPM
op_tol: !!float 5e-6
max_iter: !!int 25
# Sketchy CGAL
sketch_cgal_rank: !!int 128
duality_tol: 0.1